name: 'Hello World'
description: 'Saying hello to the world!'
author: 'Praveen and Punith'


inputs:
  commit-count:  # id of input
    description: 'commit input'
    required: true
    default: '4'
    
  LabelName: # id of input
    description: 'label name input'
    required: true
    default: 'LargePR'
  Comments: # id of input
    description: 'comment'
    required: true
    default: 'The PR should have less than 10 commits'
  github_token: #id of input
    description: 'Default Github token'
    required: true
    default: 'mytoken'
  PR_Number:
    description: 'Pull request number'
    required: true
    default: '3'
  GitHubRepository: # id of input
    description: 'fetch deafult git hub repo'
    required: true
    default: 'default repo'


outputs:
  CommitsCounts: # id of output
    description: 'The time we greeted you'
  labelname:
    description: 'label name'
  comments:
    description: 'commants description'
  Github_Token:
    description: 'github token'
  pr_number:
    description: 'pull request number'
    
    
runs:
  using: 'node12'
  main: 'index.js'
  post: 'index.js'
